package com.kanaxis.sms.model;

// Generated Sep 17, 2015 6:41:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admission generated by hbm2java
 */
@Entity
@Table(name = "admission", catalog = "sms")
public class Admission implements java.io.Serializable {

	private Integer id;
	private Double admissionNum;
	private Date admissionDate;
	private String firstName;
	private String lastName;
	private String class_;
	private Date dateOfBirth;
	private String gender;
	private String bloodGroup;
	private String birthPlace;
	private String nationality;
	private String religion;
	private String castCategory;
	private Boolean physicalDisability;
	private String subcast;
	private String motherToungue;
	private String localAddress;
	private String city;
	private String state;
	private Double pincode;
	private String permAddress;
	private String permCity;
	private String permState;
	private Double permPincode;
	private String phoneNumber;
	private String email;
	private String image;
	private String motherFullName;
	private String motherOccupation;
	private String motherEducation;
	private Double motherIncome;
	private String fatherFullName;
	private String fatherOccupation;
	private String fatherEducation;
	private Double fatherIncome;
	private Boolean parentAsGuardian;
	private String primaryContactNum;
	private String secondaryContactNumber;
	private String prevInstitution;
	private String year;
	private String previousClass;
	private Double totalMarks;
	private Double marksObtained;

	public Admission() {
	}

	public Admission(String firstName, String lastName, String class_,
			Date dateOfBirth, String gender, String bloodGroup,
			String birthPlace, String nationality, String motherToungue,
			String phoneNumber, String email) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.class_ = class_;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.bloodGroup = bloodGroup;
		this.birthPlace = birthPlace;
		this.nationality = nationality;
		this.motherToungue = motherToungue;
		this.phoneNumber = phoneNumber;
		this.email = email;
	}

	public Admission(Double admissionNum, Date admissionDate, String firstName,
			String lastName, String class_, Date dateOfBirth, String gender,
			String bloodGroup, String birthPlace, String nationality,
			String religion, String castCategory, Boolean physicalDisability,
			String subcast, String motherToungue, String localAddress,
			String city, String state, Double pincode, String permAddress,
			String permCity, String permState, Double permPincode,
			String phoneNumber, String email, String image,
			String motherFullName, String motherOccupation,
			String motherEducation, Double motherIncome, String fatherFullName,
			String fatherOccupation, String fatherEducation,
			Double fatherIncome, Boolean parentAsGuardian,
			String primaryContactNum, String secondaryContactNumber,
			String prevInstitution, String year, String previousClass,
			Double totalMarks, Double marksObtained) {
		this.admissionNum = admissionNum;
		this.admissionDate = admissionDate;
		this.firstName = firstName;
		this.lastName = lastName;
		this.class_ = class_;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.bloodGroup = bloodGroup;
		this.birthPlace = birthPlace;
		this.nationality = nationality;
		this.religion = religion;
		this.castCategory = castCategory;
		this.physicalDisability = physicalDisability;
		this.subcast = subcast;
		this.motherToungue = motherToungue;
		this.localAddress = localAddress;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
		this.permAddress = permAddress;
		this.permCity = permCity;
		this.permState = permState;
		this.permPincode = permPincode;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.image = image;
		this.motherFullName = motherFullName;
		this.motherOccupation = motherOccupation;
		this.motherEducation = motherEducation;
		this.motherIncome = motherIncome;
		this.fatherFullName = fatherFullName;
		this.fatherOccupation = fatherOccupation;
		this.fatherEducation = fatherEducation;
		this.fatherIncome = fatherIncome;
		this.parentAsGuardian = parentAsGuardian;
		this.primaryContactNum = primaryContactNum;
		this.secondaryContactNumber = secondaryContactNumber;
		this.prevInstitution = prevInstitution;
		this.year = year;
		this.previousClass = previousClass;
		this.totalMarks = totalMarks;
		this.marksObtained = marksObtained;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "admission_num", precision = 22, scale = 0)
	public Double getAdmissionNum() {
		return this.admissionNum;
	}

	public void setAdmissionNum(Double admissionNum) {
		this.admissionNum = admissionNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "admission_date", length = 10)
	public Date getAdmissionDate() {
		return this.admissionDate;
	}

	public void setAdmissionDate(Date admissionDate) {
		this.admissionDate = admissionDate;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "class", nullable = false, length = 45)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", nullable = false, length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "gender", nullable = false, length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "blood_group", nullable = false, length = 45)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name = "birth_place", nullable = false, length = 45)
	public String getBirthPlace() {
		return this.birthPlace;
	}

	public void setBirthPlace(String birthPlace) {
		this.birthPlace = birthPlace;
	}

	@Column(name = "nationality", nullable = false, length = 45)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "religion", length = 45)
	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	@Column(name = "cast_category", length = 45)
	public String getCastCategory() {
		return this.castCategory;
	}

	public void setCastCategory(String castCategory) {
		this.castCategory = castCategory;
	}

	@Column(name = "physical_disability")
	public Boolean getPhysicalDisability() {
		return this.physicalDisability;
	}

	public void setPhysicalDisability(Boolean physicalDisability) {
		this.physicalDisability = physicalDisability;
	}

	@Column(name = "subcast", length = 45)
	public String getSubcast() {
		return this.subcast;
	}

	public void setSubcast(String subcast) {
		this.subcast = subcast;
	}

	@Column(name = "mother_toungue", nullable = false, length = 45)
	public String getMotherToungue() {
		return this.motherToungue;
	}

	public void setMotherToungue(String motherToungue) {
		this.motherToungue = motherToungue;
	}

	@Column(name = "local_address", length = 100)
	public String getLocalAddress() {
		return this.localAddress;
	}

	public void setLocalAddress(String localAddress) {
		this.localAddress = localAddress;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "pincode", precision = 22, scale = 0)
	public Double getPincode() {
		return this.pincode;
	}

	public void setPincode(Double pincode) {
		this.pincode = pincode;
	}

	@Column(name = "perm_address", length = 100)
	public String getPermAddress() {
		return this.permAddress;
	}

	public void setPermAddress(String permAddress) {
		this.permAddress = permAddress;
	}

	@Column(name = "perm_city", length = 45)
	public String getPermCity() {
		return this.permCity;
	}

	public void setPermCity(String permCity) {
		this.permCity = permCity;
	}

	@Column(name = "perm_state", length = 45)
	public String getPermState() {
		return this.permState;
	}

	public void setPermState(String permState) {
		this.permState = permState;
	}

	@Column(name = "perm_pincode", precision = 22, scale = 0)
	public Double getPermPincode() {
		return this.permPincode;
	}

	public void setPermPincode(Double permPincode) {
		this.permPincode = permPincode;
	}

	@Column(name = "phone_number", nullable = false, length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "image", length = 65535)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "mother_full_name", length = 45)
	public String getMotherFullName() {
		return this.motherFullName;
	}

	public void setMotherFullName(String motherFullName) {
		this.motherFullName = motherFullName;
	}

	@Column(name = "mother_occupation", length = 45)
	public String getMotherOccupation() {
		return this.motherOccupation;
	}

	public void setMotherOccupation(String motherOccupation) {
		this.motherOccupation = motherOccupation;
	}

	@Column(name = "mother_education", length = 45)
	public String getMotherEducation() {
		return this.motherEducation;
	}

	public void setMotherEducation(String motherEducation) {
		this.motherEducation = motherEducation;
	}

	@Column(name = "mother_income", precision = 22, scale = 0)
	public Double getMotherIncome() {
		return this.motherIncome;
	}

	public void setMotherIncome(Double motherIncome) {
		this.motherIncome = motherIncome;
	}

	@Column(name = "father_full_name", length = 45)
	public String getFatherFullName() {
		return this.fatherFullName;
	}

	public void setFatherFullName(String fatherFullName) {
		this.fatherFullName = fatherFullName;
	}

	@Column(name = "father_occupation", length = 50)
	public String getFatherOccupation() {
		return this.fatherOccupation;
	}

	public void setFatherOccupation(String fatherOccupation) {
		this.fatherOccupation = fatherOccupation;
	}

	@Column(name = "father_education", length = 45)
	public String getFatherEducation() {
		return this.fatherEducation;
	}

	public void setFatherEducation(String fatherEducation) {
		this.fatherEducation = fatherEducation;
	}

	@Column(name = "father_income", precision = 22, scale = 0)
	public Double getFatherIncome() {
		return this.fatherIncome;
	}

	public void setFatherIncome(Double fatherIncome) {
		this.fatherIncome = fatherIncome;
	}

	@Column(name = "parent_as_guardian")
	public Boolean getParentAsGuardian() {
		return this.parentAsGuardian;
	}

	public void setParentAsGuardian(Boolean parentAsGuardian) {
		this.parentAsGuardian = parentAsGuardian;
	}

	@Column(name = "primary_contact_num", length = 45)
	public String getPrimaryContactNum() {
		return this.primaryContactNum;
	}

	public void setPrimaryContactNum(String primaryContactNum) {
		this.primaryContactNum = primaryContactNum;
	}

	@Column(name = "secondary_contact_number", length = 45)
	public String getSecondaryContactNumber() {
		return this.secondaryContactNumber;
	}

	public void setSecondaryContactNumber(String secondaryContactNumber) {
		this.secondaryContactNumber = secondaryContactNumber;
	}

	@Column(name = "prev_institution", length = 45)
	public String getPrevInstitution() {
		return this.prevInstitution;
	}

	public void setPrevInstitution(String prevInstitution) {
		this.prevInstitution = prevInstitution;
	}

	@Column(name = "year", length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "previous_class", length = 45)
	public String getPreviousClass() {
		return this.previousClass;
	}

	public void setPreviousClass(String previousClass) {
		this.previousClass = previousClass;
	}

	@Column(name = "total_marks", precision = 22, scale = 0)
	public Double getTotalMarks() {
		return this.totalMarks;
	}

	public void setTotalMarks(Double totalMarks) {
		this.totalMarks = totalMarks;
	}

	@Column(name = "marks_obtained", precision = 22, scale = 0)
	public Double getMarksObtained() {
		return this.marksObtained;
	}

	public void setMarksObtained(Double marksObtained) {
		this.marksObtained = marksObtained;
	}

}
