package com.kanaxis.sms.model;

// Generated Nov 8, 2015 4:22:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendance generated by hbm2java
 */
@Entity
@Table(name = "attendance", catalog = "sms")
public class Attendance implements java.io.Serializable {

	private Integer id;
	private Section section;
	private Student student;
	private Classes classes;
	private Boolean status;
	private Date dateOfAbsent;
	private Boolean weeklyStatus;
	private Boolean monthlyStatus;

	public Attendance() {
	}

	public Attendance(Section section, Student student, Classes classes,
			Boolean status, Date dateOfAbsent, Boolean weeklyStatus,
			Boolean monthlyStatus) {
		this.section = section;
		this.student = student;
		this.classes = classes;
		this.status = status;
		this.dateOfAbsent = dateOfAbsent;
		this.weeklyStatus = weeklyStatus;
		this.monthlyStatus = monthlyStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_id")
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "st_id")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classes_id")
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateOfAbsent", length = 10)
	public Date getDateOfAbsent() {
		return this.dateOfAbsent;
	}

	public void setDateOfAbsent(Date dateOfAbsent) {
		this.dateOfAbsent = dateOfAbsent;
	}

	@Column(name = "weekly_status")
	public Boolean getWeeklyStatus() {
		return this.weeklyStatus;
	}

	public void setWeeklyStatus(Boolean weeklyStatus) {
		this.weeklyStatus = weeklyStatus;
	}

	@Column(name = "monthly_status")
	public Boolean getMonthlyStatus() {
		return this.monthlyStatus;
	}

	public void setMonthlyStatus(Boolean monthlyStatus) {
		this.monthlyStatus = monthlyStatus;
	}

}
