package com.kanaxis.sms.model;

// Generated Sep 10, 2015 9:11:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name = "classes", catalog = "sms")

public class Classes implements java.io.Serializable {

	private Integer id;
	private String className;
	private Set<Timetable> timetables = new HashSet<Timetable>(0);
	private Set<Examschedule> examschedules = new HashSet<Examschedule>(0);
	private Set<Subject> subjects = new HashSet<Subject>(0);
	private Set<Student> students = new HashSet<Student>(0);
	private Set<TransactionReport> transactionReports = new HashSet<TransactionReport>(
			0);
	private Set<Section> sections = new HashSet<Section>(0);
	private Set<ClassSubjectTeacherMapping> classSubjectTeacherMappings = new HashSet<ClassSubjectTeacherMapping>(
			0);

	public Classes() {
	}

	public Classes(String className, Set<Timetable> timetables,
			Set<Examschedule> examschedules, Set<Subject> subjects,
			Set<Student> students, Set<TransactionReport> transactionReports,
			Set<Section> sections,
			Set<ClassSubjectTeacherMapping> classSubjectTeacherMappings) {
		this.className = className;
		this.timetables = timetables;
		this.examschedules = examschedules;
		this.subjects = subjects;
		this.students = students;
		this.transactionReports = transactionReports;
		this.sections = sections;
		this.classSubjectTeacherMappings = classSubjectTeacherMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "class_name", length = 45)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<Timetable> getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set<Timetable> timetables) {
		this.timetables = timetables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<Examschedule> getExamschedules() {
		return this.examschedules;
	}

	public void setExamschedules(Set<Examschedule> examschedules) {
		this.examschedules = examschedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<Subject> getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set<Subject> subjects) {
		this.subjects = subjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<TransactionReport> getTransactionReports() {
		return this.transactionReports;
	}

	public void setTransactionReports(Set<TransactionReport> transactionReports) {
		this.transactionReports = transactionReports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<Section> getSections() {
		return this.sections;
	}

	public void setSections(Set<Section> sections) {
		this.sections = sections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<ClassSubjectTeacherMapping> getClassSubjectTeacherMappings() {
		return this.classSubjectTeacherMappings;
	}

	public void setClassSubjectTeacherMappings(
			Set<ClassSubjectTeacherMapping> classSubjectTeacherMappings) {
		this.classSubjectTeacherMappings = classSubjectTeacherMappings;
	}

}
