package com.kanaxis.sms.model;

// Generated Sep 17, 2015 6:41:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Days generated by hbm2java
 */
@Entity
@Table(name = "days", catalog = "sms")
public class Days implements java.io.Serializable {

	private Integer id;
	private String day;
	private Set<Timetable> timetables = new HashSet<Timetable>(0);

	public Days() {
	}

	public Days(String day, Set<Timetable> timetables) {
		this.day = day;
		this.timetables = timetables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "day", length = 45)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "days")
	public Set<Timetable> getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set<Timetable> timetables) {
		this.timetables = timetables;
	}

}
