package com.kanaxis.sms.model;

// Generated Sep 6, 2015 11:22:28 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Exams generated by hbm2java
 */
@Entity
@Table(name = "exams", catalog = "sms")
public class Exams implements java.io.Serializable {

	private Integer id;
	private String exType;

	public Exams() {
	}

	public Exams(String exType) {
		this.exType = exType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ex_type", length = 45)
	public String getExType() {
		return this.exType;
	}

	public void setExType(String exType) {
		this.exType = exType;
	}

}
