package com.kanaxis.sms.model;

// Generated Sep 10, 2015 9:11:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examschedule generated by hbm2java
 */
@Entity
@Table(name = "examschedule", catalog = "sms")
public class Examschedule implements java.io.Serializable {

	private Integer id;
	private Subject subject;
	private Messagetype messagetype;
	private Examtype examtype;
	private Classes classes;
	private Date examdate;
	private String startTime;
	private String endTime;
	private Date createddate;

	public Examschedule() {
	}

	public Examschedule(Subject subject, Messagetype messagetype,
			Examtype examtype, Classes classes, Date examdate,
			String startTime, String endTime, Date createddate) {
		this.subject = subject;
		this.messagetype = messagetype;
		this.examtype = examtype;
		this.classes = classes;
		this.examdate = examdate;
		this.startTime = startTime;
		this.endTime = endTime;
		this.createddate = createddate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "messagetype_id")
	public Messagetype getMessagetype() {
		return this.messagetype;
	}

	public void setMessagetype(Messagetype messagetype) {
		this.messagetype = messagetype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examtype_id")
	public Examtype getExamtype() {
		return this.examtype;
	}

	public void setExamtype(Examtype examtype) {
		this.examtype = examtype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "examdate", length = 10)
	public Date getExamdate() {
		return this.examdate;
	}

	public void setExamdate(Date examdate) {
		this.examdate = examdate;
	}

	@Column(name = "start_time", length = 45)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_time", length = 45)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

}
