package com.kanaxis.sms.model;

// Generated Oct 18, 2015 2:37:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Examtype generated by hbm2java
 */
@Entity
@Table(name = "examtype", catalog = "sms")
public class Examtype implements java.io.Serializable {

	private Integer id;
	private String exType;
	private Set<Examschedule> examschedules = new HashSet<Examschedule>(0);
	private Set<MarksTable> marksTables = new HashSet<MarksTable>(0);
	private Set<TotalMarks> totalMarkses = new HashSet<TotalMarks>(0);

	public Examtype() {
	}

	public Examtype(String exType, Set<Examschedule> examschedules,
			Set<MarksTable> marksTables, Set<TotalMarks> totalMarkses) {
		this.exType = exType;
		this.examschedules = examschedules;
		this.marksTables = marksTables;
		this.totalMarkses = totalMarkses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ex_type", length = 45)
	public String getExType() {
		return this.exType;
	}

	public void setExType(String exType) {
		this.exType = exType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examtype")
	public Set<Examschedule> getExamschedules() {
		return this.examschedules;
	}

	public void setExamschedules(Set<Examschedule> examschedules) {
		this.examschedules = examschedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examtype")
	public Set<MarksTable> getMarksTables() {
		return this.marksTables;
	}

	public void setMarksTables(Set<MarksTable> marksTables) {
		this.marksTables = marksTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examtype")
	public Set<TotalMarks> getTotalMarkses() {
		return this.totalMarkses;
	}

	public void setTotalMarkses(Set<TotalMarks> totalMarkses) {
		this.totalMarkses = totalMarkses;
	}

}
