package com.kanaxis.sms.model;

// Generated Nov 8, 2015 4:22:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Messagetype generated by hbm2java
 */
@Entity
@Table(name = "messagetype", catalog = "sms")
public class Messagetype implements java.io.Serializable {

	private Integer id;
	private String messageType;
	private Set<Notifications> notificationses = new HashSet<Notifications>(0);

	public Messagetype() {
	}

	public Messagetype(String messageType, Set<Notifications> notificationses) {
		this.messageType = messageType;
		this.notificationses = notificationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "message_type", length = 45)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "messagetype")
	public Set<Notifications> getNotificationses() {
		return this.notificationses;
	}

	public void setNotificationses(Set<Notifications> notificationses) {
		this.notificationses = notificationses;
	}

}
