package com.kanaxis.sms.model;

// Generated Sep 6, 2015 11:22:28 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MonthlywiseAttendance generated by hbm2java
 */
@Entity
@Table(name = "monthlywise_attendance", catalog = "sms")
public class MonthlywiseAttendance implements java.io.Serializable {

	private Integer id;
	private Student student;
	private String month;
	private Integer year;
	private Date dateOfAbsent;
	private Integer totalDaysPresent;
	private Integer totalDaysAbsent;
	private Integer numOfWorkingDays;

	public MonthlywiseAttendance() {
	}

	public MonthlywiseAttendance(Student student, String month, Integer year,
			Date dateOfAbsent, Integer totalDaysPresent,
			Integer totalDaysAbsent, Integer numOfWorkingDays) {
		this.student = student;
		this.month = month;
		this.year = year;
		this.dateOfAbsent = dateOfAbsent;
		this.totalDaysPresent = totalDaysPresent;
		this.totalDaysAbsent = totalDaysAbsent;
		this.numOfWorkingDays = numOfWorkingDays;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "st_id")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "month", length = 45)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_absent", length = 10)
	public Date getDateOfAbsent() {
		return this.dateOfAbsent;
	}

	public void setDateOfAbsent(Date dateOfAbsent) {
		this.dateOfAbsent = dateOfAbsent;
	}

	@Column(name = "total_days_present")
	public Integer getTotalDaysPresent() {
		return this.totalDaysPresent;
	}

	public void setTotalDaysPresent(Integer totalDaysPresent) {
		this.totalDaysPresent = totalDaysPresent;
	}

	@Column(name = "total_days_absent")
	public Integer getTotalDaysAbsent() {
		return this.totalDaysAbsent;
	}

	public void setTotalDaysAbsent(Integer totalDaysAbsent) {
		this.totalDaysAbsent = totalDaysAbsent;
	}

	@Column(name = "num_of_working_days")
	public Integer getNumOfWorkingDays() {
		return this.numOfWorkingDays;
	}

	public void setNumOfWorkingDays(Integer numOfWorkingDays) {
		this.numOfWorkingDays = numOfWorkingDays;
	}

}
