package com.kanaxis.sms.model;

// Generated Nov 8, 2015 4:22:25 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PermissionTable generated by hbm2java
 */
@Entity
@Table(name = "permission_table", catalog = "sms")
public class PermissionTable implements java.io.Serializable {

	private Integer id;
	private String permissionName;

	public PermissionTable() {
	}

	public PermissionTable(String permissionName) {
		this.permissionName = permissionName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "permission_name", length = 45)
	public String getPermissionName() {
		return this.permissionName;
	}

	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

}
