package com.kanaxis.sms.model;

// Generated Oct 18, 2015 2:37:00 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rank generated by hbm2java
 */
@Entity
@Table(name = "rank", catalog = "sms")
public class Rank implements java.io.Serializable {

	private Integer id;
	private Student student;
	private String examType;
	private Double marksObtained;
	private Double maxMarks;
	private Integer rank;

	public Rank() {
	}

	public Rank(Student student, String examType, Double marksObtained,
			Double maxMarks, Integer rank) {
		this.student = student;
		this.examType = examType;
		this.marksObtained = marksObtained;
		this.maxMarks = maxMarks;
		this.rank = rank;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "st_id")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "exam_type", length = 45)
	public String getExamType() {
		return this.examType;
	}

	public void setExamType(String examType) {
		this.examType = examType;
	}

	@Column(name = "marks_obtained", precision = 22, scale = 0)
	public Double getMarksObtained() {
		return this.marksObtained;
	}

	public void setMarksObtained(Double marksObtained) {
		this.marksObtained = marksObtained;
	}

	@Column(name = "max_marks", precision = 22, scale = 0)
	public Double getMaxMarks() {
		return this.maxMarks;
	}

	public void setMaxMarks(Double maxMarks) {
		this.maxMarks = maxMarks;
	}

	@Column(name = "rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

}
