package com.kanaxis.sms.model;

// Generated Sep 6, 2015 11:22:28 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "sms", uniqueConstraints = @UniqueConstraint(columnNames = {
		"subject_name", "class_id" }))
public class Subject implements java.io.Serializable {

	private Integer id;
	private Classes classes;
	private String subjectName;
	private Set<Timetable> timetables = new HashSet<Timetable>(0);
	private Set<MarksTable> marksTables = new HashSet<MarksTable>(0);
	private Set<TransactionReport> transactionReports = new HashSet<TransactionReport>(
			0);
	private Set<ClassSubjectTeacherMapping> classSubjectTeacherMappings = new HashSet<ClassSubjectTeacherMapping>(
			0);

	public Subject() {
	}

	public Subject(Classes classes, String subjectName,
			Set<Timetable> timetables, Set<MarksTable> marksTables,
			Set<TransactionReport> transactionReports,
			Set<ClassSubjectTeacherMapping> classSubjectTeacherMappings) {
		this.classes = classes;
		this.subjectName = subjectName;
		this.timetables = timetables;
		this.marksTables = marksTables;
		this.transactionReports = transactionReports;
		this.classSubjectTeacherMappings = classSubjectTeacherMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@Column(name = "subject_name", length = 50)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<Timetable> getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set<Timetable> timetables) {
		this.timetables = timetables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<MarksTable> getMarksTables() {
		return this.marksTables;
	}

	public void setMarksTables(Set<MarksTable> marksTables) {
		this.marksTables = marksTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<TransactionReport> getTransactionReports() {
		return this.transactionReports;
	}

	public void setTransactionReports(Set<TransactionReport> transactionReports) {
		this.transactionReports = transactionReports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<ClassSubjectTeacherMapping> getClassSubjectTeacherMappings() {
		return this.classSubjectTeacherMappings;
	}

	public void setClassSubjectTeacherMappings(
			Set<ClassSubjectTeacherMapping> classSubjectTeacherMappings) {
		this.classSubjectTeacherMappings = classSubjectTeacherMappings;
	}

}
