package com.kanaxis.sms.model;

// Generated Sep 6, 2015 11:22:28 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Teachers generated by hbm2java
 */
@Entity
@Table(name = "teachers", catalog = "sms", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Teachers implements java.io.Serializable {

	private Integer id;
	private String teacherName;
	private String qualification;
	private String email;
	private Float experience;
	private String photo;
	private String phone1;
	private String phone2;
	private String address;
	private Date joiningDate;
	private Boolean status;
	private String gender;
	private String jobTitle;
	private Date createdDate;
	private Set<Timetable> timetables = new HashSet<Timetable>(0);
	private Set<ClassSubjectTeacherMapping> classSubjectTeacherMappings = new HashSet<ClassSubjectTeacherMapping>(
			0);

	public Teachers() {
	}

	public Teachers(String teacherName, String qualification, String email,
			Float experience, String photo, String phone1, String phone2,
			String address, Date joiningDate, Boolean status, String gender,
			String jobTitle, Date createdDate, Set<Timetable> timetables,
			Set<ClassSubjectTeacherMapping> classSubjectTeacherMappings) {
		this.teacherName = teacherName;
		this.qualification = qualification;
		this.email = email;
		this.experience = experience;
		this.photo = photo;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.address = address;
		this.joiningDate = joiningDate;
		this.status = status;
		this.gender = gender;
		this.jobTitle = jobTitle;
		this.createdDate = createdDate;
		this.timetables = timetables;
		this.classSubjectTeacherMappings = classSubjectTeacherMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "teacher_name", length = 45)
	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	@Column(name = "qualification", length = 45)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "email", unique = true, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "experience", precision = 12, scale = 0)
	public Float getExperience() {
		return this.experience;
	}

	public void setExperience(Float experience) {
		this.experience = experience;
	}

	@Column(name = "photo", length = 45)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "phone1", length = 45)
	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	@Column(name = "phone2", length = 45)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "joining_date", length = 19)
	public Date getJoiningDate() {
		return this.joiningDate;
	}

	public void setJoiningDate(Date joiningDate) {
		this.joiningDate = joiningDate;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "job_title", length = 45)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teachers")
	public Set<Timetable> getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set<Timetable> timetables) {
		this.timetables = timetables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teachers")
	public Set<ClassSubjectTeacherMapping> getClassSubjectTeacherMappings() {
		return this.classSubjectTeacherMappings;
	}

	public void setClassSubjectTeacherMappings(
			Set<ClassSubjectTeacherMapping> classSubjectTeacherMappings) {
		this.classSubjectTeacherMappings = classSubjectTeacherMappings;
	}

}
